### ISSUE TITLE
Unnecessary response urldecoding fails if response JSON is not a valid urlencoded string

### ISSUE THREAD

**Issue by kalinochkind** [emailage/Emailage_Java#40]
`QueryEmail` method applies `java.net.URLDecoder.decode` to the response. However, the response is a JSON, not an urlencoded string. 

In most cases this is a no-op, but sometimes it can fail. For example, if the response JSON contains the following location value: `"location":"%"`
then response parsing fails with the following exception:

```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "","
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:237)
	at java.base/java.net.URLDecoder.decode(URLDecoder.java:147)
	at com.emailage.javawrapper.EmailageClient.QueryEmail(EmailageClient.java:91)
...
```

**Comment by RobGeorgeMM** [comment]
Hi @kalinochkind, this has obviously been some delay, but has bee been resolved in version 1.2.5, thanks
